name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests (if any)
      run: npm test || echo "No tests to run"

    - name: Build Docker image
      run: docker build . -t devsecops-project
# Step 4: Start the target service
    - name: Start the target service
      run: |
        npm start &  # Start the service in the background
# Step 5: Wait for the service to be fully initialized
    - name: Wait for the service to start
      run: sleep 15  # Adjust the sleep duration as needed
    # Step 6: Run ZAP Baseline Scan
    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.13.0
      with:
        target: 'http://localhost:3000'  # URL of the service to scan
        format: 'json'                   # Format of the report
        output: 'zap_report.json' 